export const GET_STUDENT = 'GET_STUDENT';
export const GET_STUDENT_PROFILE = 'GET_STUDENT_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const GET_ERRORS = 'GET_ERRORS';
